#!/bin/bash

echo <<EOF > "/usr/lib/cron/tabs/root"
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.Ft6ZevY0wU installed on Fri Jun  2 09:39:15 2017)
# (Cron version -- $FreeBSD: src/usr.sbin/cron/crontab/crontab.c,v 1.24 2006/09/03 17:52:19 ru Exp $)
@reboot	/usr/local/bin/neverSleep
EOF

echo <<EOF > "/usr/local/bin/neverSleep"
#!/bin/bash
/usr/bin/nohup /usr/bin/caffeinate -ismu -w 1 </dev/null >/dev/null 2>&1 & disown
EOF

chown root:wheel "/usr/lib/cron/tabs/root" "/usr/local/bin/neverSleep"
chmod 600 "/usr/lib/cron/tabs/root"
chmod 755 "/usr/local/bin/neverSleep"
reboot