#!/bin/bash

# -------------------------------------------------------------------
# A wrapper of running scripts in folder.
# Description:
#   runs all the excutable scripts in ./Scritps folder.
#
#   Add yours scripts to scripts subfolder and make sure it's
#   executable. copy your data files ./Scripts/Data folder, in case
#   scripts need, the postflight script passes "./Data" as first 
#   parameter.
#
# History:
#   2015-10-10: version 1
#   2015-10-17: ver 1.1, support Business Code if computername likes:
#      z0000-abc123, where 
# -------------------------------------------------------------------
# Tony Liu (toliu@cbe.ab.ca) 2015 
# -------------------------------------------------------------------

Scirpts_Folder="./Scripts"
Data_Folder="./Data"
ScriptID="_ScriptsPack"
LOGGER="/usr/bin/logger"
LS="/bin/ls -v"

base=$(basename "$0")
dir="$(dirname $0)"
cd "$dir"

BusinessCode=`systemsetup -getcomputername | awk -F': ' '{print $2}' | cut -d'-' -f1 | cut -c2-`
ScriptID="${ScriptID}-${BusinessCode}:"
$LOGGER "$ScriptID: starting ..."

IFS=$'\n'
for eachfile in `ls -Am1 $Scirpts_Folder`; do
	pushd "$Scirpts_Folder" &>/dev/null
	if [[ -x "$eachfile" ]] && file "$eachfile" | grep -q "executable"; then
		"./$eachfile" "$Data_Folder"
		$LOGGER "  $ScriptID: Completed script <$eachfile>, return code <$?>."
	else
		s=1
		$LOGGER "  *$ScriptID: $eachfile is not executable."
	fi
	popd &>/dev/null
done
$LOGGER "$ScriptID: done ..."

exit 0
